### PR TITLE
Adding info on disabling audio output during behave tests 

### PR DESCRIPTION
**Pull request by hughwilliams94**

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey Hugh this is an excellent addition. We'll also look into making this the default behaviour when running tests.

Another quick option for applying this config change is to use the config manager eg:
```
mycroft-config set tts.module "dummy"
mycroft-config set tts.module "mimic2"
```

To protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any contributions to our repositories. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

You will also be added to [our list of excellent human beings](https://github.com/MycroftAI/contributors)!

Please visit https://mycroft.ai/cla to initiate this one-time signing.

Thank you!

**Comment by hughwilliams94** [comment]
I've added a reference to the `mycroft-config` option and started the CLA process.

**Comment by hughwilliams94** [comment]
I've signed off the CLA

**Comment by krisgesling** [comment]
Thanks Hugh, I made another little edit, but this tip is going to save a lot of people a lot of time in testing :)

**Pull request merged**
