### PR TITLE
Added details on Coqui/Mozilla TTS usage

### PR DESCRIPTION
**Pull request by thorstenMueller**
#### Description
The existing chapter in TTS documentation about Mozilla TTS server isn't very detailed and actual. Additionally the repo is now maintained by coqui. So i've added some details on installing coqui TTS server.

#### Type of PR
- [ ] Bugfix
- [ ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ X] Documentation improvements
- [ ] Test improvements

#### Testing
Check if my described steps on setting up TTS server are working correctly.

#### Documentation
Updated existing documentation in TTS chapter.

#### CLA
Already agreed in the past.

### CODE REVIEW

**Comment by el-tocino** [comment]
Instead of enumerating the models, it may work better in the long run to simply link the model zoon?

**Comment by thorstenMueller** [comment]
> Instead of enumerating the models, it may work better in the long run to simply link the model zoon?

Might be true. I'll think about writing install command per language. In current coqui setup you don't need a download url to the model file(s).

**Comment by krisgesling** [comment]
Hey I'm going to reach out to Mozilla and just double check their position on Coqui - ie whether it's a fork or whether they've handed over and Coqui has fully adopted the project. Have you seen any formal acknowledgement from Mozilla on this?

If it's an adoption we can switch over, if it's a fork it is probably worth us adding a new section as they'll start to diverge.

Also if the information here doesn't exist on the Coqui TTS Wiki  - I think it would be a great addition there. I'd actually prefer to have it there, and for us to link to that version, because it's far more likely to stay up to date then. This was the idea behind the current link to the Mozilla TTS wiki, but I can't see an equivalent page for Coqui yet.

**Comment by thorstenMueller** [comment]
Hey Kris.

> Hey I'm going to reach out to Mozilla and just double check their position on Coqui - ie whether it's a fork or whether they've handed over and Coqui has fully adopted the project. Have you seen any formal acknowledgement from Mozilla on this?
> If it's an adoption we can switch over, if it's a fork it is probably worth us adding a new section as they'll start to diverge.

You're right. "Guessing" is good, but having a proof is better. Maybe @erogol or @kdavis-coqui can say something "official" from @coqui side, too.
 
> Also if the information here doesn't exist on the Coqui TTS Wiki - I think it would be a great addition there. I'd actually prefer to have it there, and for us to link to that version, because it's far more likely to stay up to date then. This was the idea behind the current link to the Mozilla TTS wiki, but I can't see an equivalent page for Coqui yet.

@erogol any chance to add a list of voices and install commands to wiki (https://github.com/coqui-ai/TTS/wiki/Experimental-Released-Models)? If it's helpful i can write a new md-wiki file listing as draft for this.

**Comment by kdavis-coqui** [comment]
Coqui's TTS is a fork of Mozilla's.

However, that said, @erogol, the sole developer at Mozilla who worked (past tense) on Mozilla's TTS, is no longer at Mozilla but at Coqui.

**Comment by erogol** [comment]
@thorstenMueller all models are listed here https://github.com/coqui-ai/TTS/releases

Experimental models are, as the name suggests, are experimental and I'd not prefer to push them forward.

**Comment by thorstenMueller** [comment]
Hello guys.
Thanks for your quick feedback on this 👍 . I would update PR with the following:

* Keep existing chapter "Mozilla TTS" as it is right now
* Add a new chapter for Coqui fork (primarily with the content of the existing PR)
* Remove list of available models from Mycroft doc and link to the page @erogol mentioned
* Add a description in Mycroft doc on how to install the Coqui models (from above list)

Would this be the way to go?

**Comment by krisgesling** [comment]
Indeed, thanks for clarifying Kelly and Erogol - really excited to see the team and your work continuing!

@thorstenMueller that looks right to me. 
In your new Coqui TTS section you could direct people to configure mycroft.conf using the Mozilla TTS instructions with an anchor link.

**Comment by thorstenMueller** [comment]
I've updated the PR and added new chapter Coqui TTS in addition to existing Mozilla TTS chapter.

**Comment by krisgesling** [comment]
Thanks Thorsten, I've made some additional edits - if you're happy with this we can merge it in :)

**Comment by thorstenMueller** [comment]
Sounds good for me :blush:. Feel free to merge whenever you're ready.

**Pull request merged**
