### PR TITLE
Add .md extension to relative link target

### PR DESCRIPTION
**Pull request by ceich**
#### Description
Attempted fix for #225 

#### Type of PR
- [ ] Bugfix
- [ ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [x] Documentation improvements
- [ ] Test improvements

#### Testing
Contrary to what I wrote in #225, there is an example of a relative link with an anchor already in the [source](https://github.com/MycroftAI/documentation/blob/master/docs/skill-development/mycroft-skills-manager/README.md?plain=1#L127). I am confident that adding the extension before the \# will fix the link for good.

### CODE REVIEW

**Comment by ceich** [comment]
I tested this on my personal GitBook account and the relative link is fixed. Please merge and approve?

**Comment by ceich** [comment]
@krisgesling ☝️

**Comment by krisgesling** [comment]
YOLO :D

**Comment by krisgesling** [comment]
It is a bit annoying the way that Gitbook has it's own specific quirks. Thanks for following it up!

**Pull request merged**
