### PR TITLE
corrected typos

### PR DESCRIPTION
**Pull request by ryanzidago**

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey Ryan, thanks for the updates!

It's really dependenting on how you look at it :rofl: 

This might seem over the top for little typo changes, but to protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any contributions to the project. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

It also means you will also be added to [our list of excellent human beings](https://github.com/MycroftAI/contributors) forever enshrined as a contributor to Mycroft AI!

Please visit https://mycroft.ai/cla to initiate this one-time signing.

Thanks!

**Comment by ryanzidago** [comment]
Hi Kris,

I totally understand, no problem! 
I just requested the CLA.

Thanks!

**Comment by ryanzidago** [comment]
Hi Kris,

Did you receive my 'Contributor License Agreement Request Form' ?

**Comment by krisgesling** [comment]
Hey, didn't mean for this to get closed, have been switching the branches around for our migration to https://mycroft-ai.gitbook.io/docs/

Your account hasn't been added to the contributor list though. Did you get the email from HelloSign too?

**Comment by ryanzidago** [comment]
Even after checking my spam folder, I've never received the mail from HelloSign eventhough I submitted several times the form.

**Comment by krisgesling** [comment]
Sorry about that, I'll chase it up.
It's always been a partly manual process and the person who used to manage that left. We're now working on a fully automated process as it just creates too much of a bottleneck for things to be approved.

**Pull request merged**
