### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Kaligule**

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi Kaligule - nice spotting!

To protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting and merging any contributions. This agreement makes it crystal clear that you are offering a license for Mycroft to use it. You retain ownership of any contributions, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by Kaligule** [comment]
I just did this with my real name. Are there additional steps so you can prove that it was this account who is linked to that signing?

**Comment by forslund** [comment]
In the form you received via e-mail there should be a field where you enter github username if I recall correctly. If that's where you entered your real name I think we can add the github username manually

**Comment by Kaligule** [comment]
Seems like those mails don't get send. I tried three times now with different mail adresses (including googlemail). Are you shure the mails get sent out?

**Comment by Kaligule** [comment]
For some reason it took a few days. I signed that agreement and provided my github username, so we should be fine.

**Comment by forslund** [comment]
Excellent, was going to bring this up with the people with access to see if something was wrong but now I can continue being lazy.

I'll watch the contributor list and will merge when your alias gets added.

**Comment by Kaligule** [comment]
@forslund  I don't know, emails being sent with 2 days delay might be a problem worth investigating.

**Comment by forslund** [comment]
True true, will pass it along as a possible issue.

**Pull request merged**
